name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 26.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.2"

      - name: Inspect repository
        run: |
          pwd
          ls -la
          find . -name "*.xcodeproj"
          find . -name "*.xcworkspace"

      - name: Build and test
        run: |
          PROJECT_PATH=$(find . -name "*.xcodeproj" | head -n 1)
          echo "Using project: $PROJECT_PATH"
          
          xcodebuild \
            -project "$PROJECT_PATH" \
            -scheme "UnsplashFeed_CI" \
            -destination "platform=macOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean build test
